from datetime import *

YEARS = ['2017', '2018', '2019', '2020', '2021', '2022']
INTERVALS = ["1m", "3m", "5m", "15m", "30m", "1h", "2h", "4h", "6h", "8h", "12h", "1d", "3d", "1w", "1mo"]
DAILY_INTERVALS = ["1m", "3m", "5m", "15m", "30m", "1h", "2h", "4h", "6h", "8h", "12h", "1d"]
TRADING_TYPE = ["spot", "um", "cm"]
MONTHS = list(range(1,13))
PERIOD_START_DATE = '2020-01-01'
BASE_URL = 'https://data.binance.vision/'
START_DATE = date(int(YEARS[0]), MONTHS[0], 1)
END_DATE = datetime.date(datetime.now())
SYMBOLS = ('BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'ADAUSDT', 'XRPUSDT', 'LUNAUSDT',
           'DOTUSDT', 'AVAXUSDT', 'DOGEUSDT', 'SHIBUSDT', 'MATICUSDT', 'LINKUSDT', 'UNIUSDT',
           'ALGOUSDT', 'LTCUSDT', 'NEARUSDT', 'ATOMUSDT', 'BCHUSDT', 'ICPUSDT', 'TRXUSDT',
           'XLMUSDT', 'FTMUSDT', 'MANAUSDT', 'FTTUSDT', 'VETUSDT', 'HBARUSDT', 'FILUSDT',
           'AXSUSDT', 'SANDUSDT', 'THETAUSDT', 'EGLDUSDT', 'ETCUSDT', 'XTZUSDT', 'HNTUSDT',
           'ONEUSDT', 'KLAYUSDT', 'XMRUSDT', 'IOTAUSDT', 'AAVEUSDT', 'CAKEUSDT', 'GRTUSDT',
           'EOSUSDT', 'STXUSDT', 'FLOWUSDT', 'BTTCUSDT', 'GALAUSDT', 'CRVUSDT', 'LRCUSDT',
           'KSMUSDT', 'MKRUSDT', 'QNTUSDT', 'RUNEUSDT', 'ENJUSDT', 'ZECUSDT', 'AMPUSDT',
           'CELOUSDT', 'XECUSDT', 'ARUSDT', 'NEOUSDT', 'CHZUSDT', 'BATUSDT', 'DASHUSDT',
           'WAVESUSDT', 'TUSDUSDT', 'COMPUSDT', 'YFIUSDT', 'ROSEUSDT', 'MINAUSDT', 'HOTUSDT',
           'RVNUSDT', 'XEMUSDT', 'IOTXUSDT', '1INCHUSDT', 'SCRTUSDT', 'SUSHIUSDT', 'TFUELUSDT',
           'GNOUSDT', 'BNTUSDT', 'LPTUSDT', 'WAXPUSDT', 'KDAUSDT', 'BTTUSDT', 'DAIUSDT', 'USDPUSDT',
           'ETHBTC', 'BNBBTC', 'SOLBTC', 'ADABTC', 'XRPBTC', 'DOTBTC', 'AVAXBTC', 'DOGEBTC',
           'SHIBBTC', 'MATICBTC', 'LINKBTC', 'UNIBTC', 'ALGOBTC', 'LTCBTC', 'NEARBTC', 'ATOMBTC',
           'BCHBTC', 'ICPBTC', 'TRXBTC', 'XLMBTC', 'FTMBTC', 'MANABTC', 'FTTBTC', 'VETBTC',
           'HBARBTC', 'FILBTC', 'AXSBTC', 'EOSBTC', 'MKRBTC', 'BNBETH', 'SOLETH', 'ADAETH',
           'XRPETH', 'DOTETH', 'AVAXETH', 'MATICETH', 'LTCETH', 'SOLBNB', 'ADABNB', 'XRPBNB',
           'DOTBNB', 'AVAXBNB', 'MATICBNB', 'LTCBNB'
           )
