# Generated by Django 4.0.4 on 2022-06-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('likes', models.IntegerField()),
                ('type', models.IntegerField(choices=[(1, 'Type 1'), (2, 'Type 2')])),
            ],
        ),
    ]
