# Generated by Django 4.0.4 on 2022-06-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
